# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.6
  - nightly

notifications:
  email: false

jobs:
  allow_failures:
    - julia: nightly

after_success:
  - if [[ $TRAVIS_OS_NAME = linux ]]; then
      julia --project=coverage/ -e 'using Pkg; Pkg.instantiate();
          using Coverage; Codecov.submit(Codecov.process_folder())';
    fi
